---
version: "3.8"

services:
  postgres:
    container_name: htmlfetcher-postgres
    image: postgres:13.3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: htmlfetcher
    networks:
      - all

volumes:
  postgres:

networks:
  all:
